# https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
# https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#quick-start
# https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-InitConfiguration
skipPhases:
  - addon/kube-proxy
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  # name: node
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: 1.27.2
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    audit-policy-file: /etc/kubernetes/pki/audit-policy.yaml
    audit-webhook-config-file: /etc/kubernetes/pki/audit-sink.yaml
    # service-node-port-range: 80-10000
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
