---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  interval: 10m0s
  path: ./iipod-metal/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: HelmRelease
        name: ingress-nginx
        namespace: ingress-nginx
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: ingress-nginx
        spec:
          values:
            controller:
              service:
                externalIPs:
                  - ${ip}
