    # From https://launchpad.net/~hippiehacker/+archive/ubuntu/emacs-broadway
    # emacs.list:
    #   # source: "ppa:hippiehacker/emacs-broadway"
    #   source: "deb http://ppa.launchpad.net/hippiehacker/emacs-broadway/ubuntu kinetic main"
    #   keyid: 78F37A14C8142D21 #keyid for Hippie Hacker
    #   filename: hippiehacker-emacsbroadway-ppa.list
    # write_files:
    # - path: /etc/systemd/system/coder-agent.service
    #   content: $${coder_init_service}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/cloud/wildcard.cert.pem
    #   content: $${wildcard_cert_pem}
    #   permissions: "0600"
    #   encoding: b64
    # - path: /etc/cloud/wildcard.key.pem
    #   content: $${wildcard_key_pem}
    #   permissions: "0600"
    #   encoding: b64
    # - path: /etc/kubernetes/pki/audit-policy.yaml
    #   content: $${audit_policy}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/kubernetes/pki/audit-sink.yaml
    #   content: $${audit_sink}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/kubernetes/helm/cilium-values.yaml
    #   content: $${cilium_helm_values}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/kubernetes/manifests/iipod.yaml
    #   content: $${iipod_manifest}
    #   permissions: "0644"
    #   encoding: b64
    # https://deploy.equinix.com/developers/docs/metal/networking/elastic-ips/
    # - path: /etc/kubernetes/kubeadm-config.yaml
    #   content: $${kubeadm_config}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/crictl.yaml
    #   content: $${crictl_config}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/containerd/config.toml
    #   content: $${containerd_config}
    #   permissios: "0644"
    #   encoding: b64
    # - path: /etc/nix/nix.conf
    #   content: $${nix_config}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/network/interfaces.d/elastic
    #   content: $${elastic_network_config}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/cloud/deploy-k8s
    #   content: $${deploy_k8s}
    #   permissions: "0755"
    #   encoding: b64
    # - path: /etc/cloud/install-cilium
    #   content: $${install_cilium}
    #   permissions: "0755"
    #   encoding: b64
    # - path: /etc/cloud/deploy-cilium
    #   content: $${deploy_cilium}
    #   permissions: "0755"
    #   encoding: b64
    # - path: /etc/cloud/install-nix
    #   content: $${install_nix}
    #   permissions: "0755"
    #   encoding: b64
    # - path: /etc/cloud/install-kind
    #   content: $${install_kind}
    #   permission: "0755"
    #   encoding: b64
    # - path: /etc/cloud/install-desktop
    #   content: $${install_desktop}
    #   permissions: "0755"
    #   encoding: b64
    # - path: /etc/kubernetes/manifests/cilium.yaml
    #   content: $${cilium_manifest}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/kubernetes/manifests/auditlogger.yaml
    #   content: $${auditlogger_manifest}
    #   permissions: "0644"
    #   encoding: b64
    # - path: /etc/kubernetes/manifests/snoopdb.yaml
    #   content: $${snoopdb_manifest}
    #   permissions: "0644"
    #   encoding: b64
    packages:
      - aria2
      - apt-fast
    # runcmd:
    #   - ip addr add $${elastic_ip} dev bond0:1
    #   - su - ii -c "ssh-import-id gh:$${username} gh:hh gh:heyste gh:zachmandeville"
    #   - su - git -c "ssh-import-id gh:$${username} gh:hh gh:heyste gh:zachmandeville"
    #   - DEBIAN_FRONTENT=noninteractive apt-fast -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y ttyd tmux kitty-terminfo
    #   # emacs-gtk kitty novnc websockify postgresql-client tigervnc-standalone-server asciinema silversearcher-ag direnv jq
    #   - systemctl stop ttyd
    #   - systemctl enable coder-agent
    #   - systemctl start coder-agent
    #   - sh -c "(/etc/cloud/install-cilium ; /etc/cloud/deploy-k8s ; /etc/cloud/deploy-cilium ; /etc/cloud/install-flux / etc/cloud/install-kind ) 2>&1 > /var/log/k8s-deploy.log &"
    #   - sh -c "crictl pull $${iipod_image} &"
    #   - sh -c "/etc/cloud/install-desktop 2>&1 > /var/log/install-desktop.log &"
    # final_message: "The system is finally up, after $UPTIME seconds"
